#! /usr/bin/perl -w

# this plugin checks the whitelisthost config files for the connecting
# IP address and sets the whitelisthost connection notes if found.

sub hook_connect {
  my ($self, $transaction) = @_;
  my $connection = $self->qp->connection;

  my %whitelist_hosts = map { $_ => 1 } ( $self->qp->config("whitelisthost") );
  my $more_whitelist_hosts = $self->qp->config("morewhitelisthost", "map");

  my $client_ip = $self->qp->connection->remote_ip;
  while ($client_ip) {
    if (exists($whitelist_hosts{$client_ip}) or
        exists($more_whitelist_hosts->{$client_ip}))
    {
      $self->log(LOGNOTICE,"Host $client_ip is whitelisted");
      $self->qp->connection->notes('whitelisthost', 1);
      last;
    }
    $client_ip =~ s/\d+\.?$//; # strip off another 8 bits
  }
  
  return (DECLINED);
}
